### ISSUE TITLE
Problem ze spotkaniami 100. i 99.

### ISSUE THREAD

**Issue by pawlos** [wrocnet/wrocnet.github.io#109]
Coś się popsuło?

![image](https://user-images.githubusercontent.com/1296768/29714797-f1c03c86-89a4-11e7-9b87-275dd63d63a2.png)

**Comment by pawlos** [comment]
@tpluscode możesz zerknąć na to?

**Comment by tpluscode** [comment]
wiadomo, copypasta :P
