### ISSUE TITLE
Film z prezentacji F#

### ISSUE THREAD

**Issue by tpluscode** [wrocnet/wrocnet.github.io#25]
Hej, dostałem od Marcina Malinowskiego link do nagrania prezentacji z lutowego spotkania, nagraną w Warszawie. Wychodzi na to, że jakość będzie lepsza niż to co uda się zmontować. Myślicie, żeby i tak wrzucić nasz film czy dać po prostu link to filmu z WG?

**Comment by pawlos** [comment]
@tpluscode jak uważasz - ja mam pełne zaufanie w tych kwestiach do ciebie ;) 

Moje 3gr - jeśli film jest to może nie warto poświęcać czasu na montowanie naszego - z drugiej strony mając własny my nim zarządzamy. Nie wiadomo co się stanie z tym WG.NET'a
