### ISSUE TITLE
Spotkanie 91

### ISSUE THREAD

**Issue by pawlos** [wrocnet/wrocnet.github.io#72]
- [ ] strona spotkania

Slajdy:

- [x] RevDeBug
- [ ] Azure na produkcji

Wideo:

- [x] RevDeBug
- [ ] Azure na produkcji

**Comment by tpluscode** [comment]
Ścignij proszę po materiały

**Comment by tpluscode** [comment]
Czy mamy coś do zalinkowania prelegentów? Twittera nie znalazłem. Może blog albo strona firmowa?

**Comment by pawlos** [comment]
@tpluscode done. Co do prelegentów to chyba nie mam info takiego. Jeśli chodzi o strony to możesz dać stronę RevDeBug'a oraz Homebook

**Comment by tpluscode** [comment]
@pawlos Dałeś film o Azure do przeglądnięcia Homebook'owi?

**Comment by pawlos** [comment]
Tak. Zero odzewu więc publikujemy.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Od: Tomasz PluskiewiczWysłano: niedziela, 5 marca 2017 11:53Do: wrocnet/wrocnet.github.ioOdpowiedz: wrocnet/wrocnet.github.ioDW: Paweł Łukasik; MentionTemat: Re: [wrocnet/wrocnet.github.io] Spotkanie 91 (#72)@pawlos Dałeś film o Azure do przeglądnięcia Homebook'owi?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wrocnet/wrocnet.github.io","title":"wrocnet/wrocnet.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wrocnet/wrocnet.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tpluscode in #72: @pawlos Dałeś film o Azure do przeglądnięcia Homebook'owi?"}],"action":{"name":"View Issue","url":"https://github.com/wrocnet/wrocnet.github.io/issues/72#issuecomment-284220084"}}}
